---

future_build: True
korp_backend_version: "sb-master"
korp_frontend_version: "future"

korp_backend_corpusconfig_repo: "https://github.com/CSCfi/Kielipankki-korp-corpus-config"
korp_backend_corpusconfig_version: "future"
korp_backend_corpusconfig_home: "{{ korp_git_root }}/Kielipankki-korp-backend-corpusconfigs"
korp_corpus_config_dir: "/v/corpora/config"

korp_backend_plugin_repo: "https://github.com/CSCfi/Kielipankki-korp-backend-plugins"
korp_backend_plugin_version: "main"

korp_frontend_config_repo: "https://github.com/CSCfi/Kielipankki-korp-frontend-config"
korp_frontend_config_version: "future"

korp_path: "future/korp"
korp_url: "{{ korp_domain }}/{{ korp_path }}"
